name: CI/CD - Simple (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Permisos a mvnw
        run: chmod +x mvnw

      - name: Build con tests
        run: ./mvnw -q clean package

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Subir JAR
        uses: actions/upload-artifact@v4
        with:
          name: appsegura-jar
          path: target/*.jar

  deploy_test:
    runs-on: ubuntu-latest
    needs: build_test_scan
    environment: test
    steps:
      - name: Descargar JAR
        uses: actions/download-artifact@v4
        with:
          name: appsegura-jar
          path: ./dist

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Arrancar app (perfil dev)
        run: |
          nohup java -jar ./dist/*.jar --spring.profiles.active=dev > app.log 2>&1 &
          echo $! > app.pid
          sleep 15
          tail -n 80 app.log || true

      - name: Smoke test /login
        run: |
          for i in {1..5}; do
            code=$(curl -I -s -o /dev/null -w "%{http_code}" http://localhost:8080/login || true)
            if echo "$code" | grep -E "200|302" >/dev/null; then
              echo "OK: /login -> $code"
              exit 0
            fi
            echo "Aún no responde (HTTP $code). Reintentando..."
            sleep 5
          done
          echo "Fallo smoke test. Últimas líneas del log:"
          tail -n 200 app.log || true
          exit 1

      - name: Detener app
        if: always()
        run: |
          if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
          sleep 2
          echo "Stopped."
