name: CI/CD - AppSegura

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_scan:
    name: Build, Test & Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Build (skip tests)
      run: ./mvnw -q clean package -DskipTests

    - name: Run unit tests
      run: ./mvnw -q test

    - name: OWASP Dependency-Check (security scan)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'AppSegura'
        path: '.'
        format: 'HTML'
        out: 'reports'

    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports

    - name: Upload built JAR
      uses: actions/upload-artifact@v3
      with:
        name: appsegura-jar
        path: target/*.jar

  deploy_to_test:
    name: Deploy to Test (smoke test)
    runs-on: ubuntu-latest
    needs: build_and_scan
    environment: test

    steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: appsegura-jar
        path: ./dist

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Start app (background)
      run: |
        nohup java -jar ./dist/*.jar --spring.profiles.active=dev > app.log 2>&1 &
        echo $! > app.pid
        sleep 15
        tail -n 50 app.log

    - name: Smoke test (login page reachable)
      run: |
        for i in {1..5}; do
          curl -I -s -o /dev/null -w "%{http_code}\n" http://localhost:8080/login | grep -E "200|302" && exit 0
          sleep 5
        done
        echo "Smoke test failed"
        tail -n 200 app.log
        exit 1

    - name: Stop app
      if: always()
      run: |
        if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
        sleep 3
        echo "Stopped."
