name: CI/CD - AppSegura (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a mvnw
        run: chmod +x mvnw

      - name: Build (skip tests)
        run: ./mvnw -q clean package -DskipTests

      - name: Run unit tests
        run: ./mvnw -q test

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'AppSegura'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Subir reporte de seguridad
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports

      - name: Subir JAR construido
        uses: actions/upload-artifact@v3
        with:
          name: appsegura-jar
          path: target/*.jar

  deploy_test:
    runs-on: ubuntu-latest
    needs: build_test_scan
    environment: test
    steps:
      - name: Descargar JAR
        uses: actions/download-artifact@v3
        with:
          name: appsegura-jar
          path: ./dist

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Arrancar app (background, perfil dev)
        run: |
          nohup java -jar ./dist/*.jar --spring.profiles.active=dev > app.log 2>&1 &
          echo $! > app.pid
          sleep 15
          tail -n 80 app.log

      - name: Smoke test (/login)
        run: |
          for i in {1..5}; do
            code=$(curl -I -s -o /dev/null -w "%{http_code}" http://localhost:8080/login || true)
            if echo "$code" | grep -E "200|302" >/dev/null; then
              echo "OK: /login respondió $code"
              exit 0
            fi
            echo "Intento $i: aún no responde (HTTP $code). Reintentando..."
            sleep 5
          done
          echo "Fallo: /login no respondió 200/302"
          tail -n 200 app.log
          exit 1

      - name: Detener ap
