name: CI/CD - Simple (master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Permisos a mvnw
        run: chmod +x mvnw

      # Build + unit tests
      - name: Build
        run: ./mvnw -q clean package

      # Security scan con Trivy (rápido y confiable)
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'     # no falla el build por findings (puedes poner 1 si quieres que falle)
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Subir JAR
        uses: actions/upload-artifact@v3
        with:
          name: appsegura-jar
          path: target/*.jar

  deploy_test:
    runs-on: ubuntu-latest
    needs: build_test_scan
    environment: test
    steps:
      - name: Descargar JAR
        uses: actions/download-artifact@v3
        with:
          name: appsegura-jar
          path: ./dist

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Arrancar app (perfil dev)
        run: |
          no
